language: c

cache:
  directories:
  - $TRAVIS_BUILD_DIR/arduino

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  # - chmod -R 755 HomeAutomation_Arduino
  - wget http://downloads.arduino.cc/arduino-1.6.13-linux64.tar.xz
  - tar -xvf arduino-1.6.13-linux64.tar.xz
  - mv arduino-1.6.13 arduino

install:
  - arduino/.arduino --install-library "ArduinoJson:5.13.0"

script:
  - arduino/./arduino --verify --board arduino:avr:uno $TRAVIS_BUILD_DIR/HomeAutomation_Arduino/HomeAutomation_Arduino.ino