language: android
jdk: oraclejdk8
    
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle

android:
    components:
        - tools
        - platform-tools
        - build-tools-27.0.3
        - build-tools-26.0.2
        - android-27
        - android-26

    licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
        - 'android-sdk-license-2742d1c5'

before_install:
    - bundle update
    - bundle install

before_script:
    - cd Android-App

script:
    - bundle exec fastlane build
    - bundle exec fastlane test

after_success:
    - bundle exec fastlane increment build_number:$TRAVIS_BUILD_NUMBER

before_deploy:
    - ./gradlew assembleDebug

before_deploy:
    - bundle exec fastlane release commit_message:$TRAVIS_COMMIT_MESSAGE