language: node_js

node_js:
    - "node"

cache:
  directories:
    - "node_modules"

before_install:
    - cd NodeServices

# after_success:
#     - bundle exec fastlane increment build_number:$TRAVIS_BUILD_NUMBER

# before_deploy:
#     - bundle exec fastlane release commit_message:$TRAVIS_COMMIT_MESSAGE