language: node_js

node_js:
    - "node"

cache:
  directories:
    - "node_modules"

before_install:
    - cd NodeServices

script:
    - node -v

deploy:
    provider: heroku
    api_key: "e9911358-938e-48b8-acd0-491a73e5cea2"
    app: "daksh-home-automation"
    on: "nodejs"



# after_success:
#     - bundle exec fastlane increment build_number:$TRAVIS_BUILD_NUMBER

# before_deploy:
#     - bundle exec fastlane release commit_message:$TRAVIS_COMMIT_MESSAGE