language: android
jdk: oraclejdk8

script: Android-App/./gradlew build connectedCheck

android:
    components:
        #- tools
        #- platform-tools
        - build-tools:27.0.3
        - android-27