language: android
jdk: oraclejdk8

android:
    components:
        #- tools
        #- platform-tools
        - build-tools:27.0.3
        - android-27

before_script:
    - cd Android-App

script:
    - ./gradlew clean
    - ./gradlew build
    - ./gradlew test

after_success:
    - bundle exec fastlane increment build_number:$TRAVIS_BUILD_NUMBER

before_deploy:
    - ./gradlew assembleDebug

before_deploy:
    - bundle exec fastlane release commit_message:$TRAVIS_COMMIT_MESSAGE