# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  	# Clean the Build Only useful when entire flow being executed
  	desc "Cleans the build"
  	lane :clean do
  		gradle(task: "clean")
    end

	desc "Runs all the tests"
	lane :test do
		gradle(task: "test")
	end

	# Increment the build number in the versionCode text file. Data from this file is fetched and used to apply
	# versionCode information in build.gradle file
  	desc "Increment build number"
 	lane :increment do
		# Get the last version code and increment it.
		versionCode = File.read("../versionCode").split('=')[1].to_i
		versionCode = versionCode + 1

		versionCodeFile = File.new("../versionCode", "w")
		versionInfo = "VERSION_CODE=#{versionCode}"
		versionCodeFile.write(versionInfo)
		versionCodeFile.close
	end

	#Hockey app for alpha deployment
    desc "Deploy a new beta version to HockeyApp"
    lane :beta do
        gradle(task: "assembleDebug")
        hockey(
            api_token: "5a4174c71f0e4905be4a90036b60db2a",
            status: "2", #Download status: "1" = No user can download; "2" = Available for download (only possible with full-access token)  
            release_type: "2", #Release type of the app: "0" = Beta (default), "1" = Store, "2" = Alpha, "3" = Enterprise
            apk: "./app/build/outputs/apk/debug/app-debug.apk"
        )
    end

	# desc "Deploy a new version to the Google Play"
	# lane :deploy do
	# 	upload_to_play_store
	# end
end
